# Generated by Django 5.2.17 on 2026-09-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts_platform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformalertconfiguration",
            name="anchor_time",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="platformalertconfiguration",
            name="recurrence_unit",
            field=models.CharField(
                blank=True,
                choices=[("day", "Day"), ("week", "Week"), ("month", "Month")],
                max_length=8,
                null=True,
            ),
        ),
    ]
