# Generated by Django 5.2.17 on 2026-09-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replay_vision", "0101_replayscanner_prompt_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replayscanner",
            name="scanner_type",
            field=models.CharField(
                choices=[
                    ("monitor", "Monitor"),
                    ("classifier", "Classifier"),
                    ("scorer", "Scorer"),
                    ("summarizer", "Summarizer"),
                    ("experiment", "Experiment"),
                ],
                max_length=32,
            ),
        ),
    ]
